framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: monifus/app

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis (recommended for production)
        # app: cache.adapter.redis
        # default_redis_provider: '%env(default:default_redis_url:REDIS_URL)%'

        # Filesystem cache (development default)
        app: cache.adapter.filesystem

        # Namespaced pools use the above "app" backend by default
        pools:
            app.cache.statistics:
                adapter: cache.app
                default_lifetime: 300 # 5 minutes for statistics

when@dev:
    framework:
        cache:
            # Use filesystem cache in development if Redis not available
            app: cache.adapter.filesystem

when@test:
    framework:
        cache:
            # Use array cache for tests
            app: cache.adapter.array
